name: Custom Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        run: echo Setting up environment...
      - name: Display greeting
        run: echo Hello from GitHub Actions!
      - name: Custom debug message
        run: echo Debugging by may tran, a test action!.
